# Generated by Django 5.1.4 on 2026-08-26 21:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1)),
                ('xp', models.PositiveIntegerField(default=0)),
                ('rank', models.CharField(choices=[('E', 'E-Rank'), ('D', 'D-Rank'), ('C', 'C-Rank'), ('B', 'B-Rank'), ('A', 'A-Rank'), ('S', 'S-Rank')], default='E', max_length=2)),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('last_workout_date', models.DateField(blank=True, null=True)),
                ('stat_str', models.PositiveIntegerField(default=0)),
                ('stat_vit', models.PositiveIntegerField(default=0)),
                ('stat_agi', models.PositiveIntegerField(default=0)),
                ('stat_end', models.PositiveIntegerField(default=0)),
                ('stat_flx', models.PositiveIntegerField(default=0)),
                ('stat_per', models.PositiveIntegerField(default=0)),
                ('fitness_goal', models.CharField(choices=[('strength', 'Strength'), ('endurance', 'Endurance'), ('flexibility', 'Flexibility')], default='strength', max_length=20)),
                ('experience_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
