# Generated by Django 5.1.4 on 2026-09-10 18:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('calories', models.PositiveIntegerField(default=0)),
                ('protein_g', models.PositiveIntegerField(default=0)),
                ('carbs_g', models.PositiveIntegerField(default=0)),
                ('fat_g', models.PositiveIntegerField(default=0)),
                ('water_ml', models.PositiveIntegerField(default=0)),
                ('calorie_target', models.PositiveIntegerField(default=2200)),
                ('protein_target_g', models.PositiveIntegerField(default=160)),
                ('carbs_target_g', models.PositiveIntegerField(default=220)),
                ('fat_target_g', models.PositiveIntegerField(default=70)),
                ('water_target_ml', models.PositiveIntegerField(default=3000)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
