# Generated by Django 5.1.4 on 2026-08-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('shoulders', 'Shoulders'), ('legs', 'Legs'), ('arms', 'Arms'), ('core', 'Core'), ('full_body', 'Full Body'), ('cardio', 'Cardio'), ('flexibility', 'Flexibility')], max_length=20)),
                ('equipment', models.CharField(choices=[('barbell', 'Barbell'), ('dumbbell', 'Dumbbell'), ('machine', 'Machine'), ('cable', 'Cable'), ('bodyweight', 'Bodyweight'), ('band', 'Resistance Band'), ('cardio_machine', 'Cardio Machine'), ('kettlebell', 'Kettlebell'), ('none', 'None')], max_length=20)),
                ('default_stat', models.CharField(choices=[('STR', 'Strength'), ('VIT', 'Vitality'), ('AGI', 'Agility'), ('END', 'Endurance'), ('FLX', 'Flexibility'), ('PER', 'Perception')], max_length=3)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
